
- name: Install git
  action: >
    {{ ansible_pkg_mgr }} name="git" state="present"
  sudo: true

- name: Install jq
  get_url:
    url: http://stedolan.github.io/jq/download/linux64/jq
    dest: /usr/bin
    mode: 0775
  sudo: true
